# Generated by Django 6.0.7 on 2026-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="country",
        ),
        migrations.AddField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(default="", help_text="Укажите отчество", max_length=150, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(help_text="Укажите имя", max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(help_text="Укажите фамилию", max_length=150, verbose_name="Фамилия"),
        ),
    ]
