# Generated by Django 6.0.7 on 2026-07-29 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите краткое наименование направления диагностики",
                        max_length=50,
                        verbose_name="Краткое наименование направления диагностики",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите полное наименование направления диагностики",
                        max_length=150,
                        verbose_name="Полное наименование направления диагностики",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "last_name",
                    models.CharField(help_text="Укажите фамилию врача", max_length=50, verbose_name="Фамилия"),
                ),
                ("first_name", models.CharField(help_text="Укажите имя врача", max_length=50, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(help_text="Укажите отчество врача", max_length=50, verbose_name="Отчество"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("highest", "Высшая категория"),
                            ("first", "Первая категория"),
                            ("second", "Вторая категория"),
                            ("without", "Без категории"),
                        ],
                        default="without",
                        help_text="Выберите категорию врача",
                        max_length=7,
                        verbose_name="Категория врача",
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите стаж работы врача", verbose_name="Стаж работы"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        help_text="Укажите специальность врача", max_length=50, verbose_name="Специальность"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        default="media/foto_doctor/default.jpg",
                        help_text="Прикрепите фотографию врача",
                        null=True,
                        upload_to="media/foto_doctor",
                        verbose_name="Фотография врача",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        help_text="Выберите направление диагностики",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direction_doctor",
                        to="meddiag.direction",
                        verbose_name="Направление диагностики",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
                "ordering": ["last_name", "specialization"],
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите краткое наименование услуги",
                        max_length=50,
                        verbose_name="Краткое наименование услуги",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите полное наименование услуги",
                        max_length=200,
                        verbose_name="Полное наименование услуги",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Укажите описание медицинской услуги",
                        null=True,
                        verbose_name="Описание услуги",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите стоимость медицинской услуги", verbose_name="Стоимость услуги"
                    ),
                ),
                (
                    "duration_execution",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Укажите продолжительность выполнения медицинской услуги в минутах",
                        verbose_name="Продолжительность услуги в минутах",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        help_text="Выберите направление медицинской диагностики",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direction_name",
                        to="meddiag.direction",
                        verbose_name="Направление диагностики",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активная"), ("rendered", "Оказана"), ("cancel", "Отменена")],
                        default="active",
                        max_length=8,
                        verbose_name="Статус услуги",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        help_text="Укажите время оказания услуги", verbose_name="Время оказания услуги"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Выберите пациента",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Выберите врача",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor",
                        to="meddiag.doctors",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "services",
                    models.ForeignKey(
                        help_text="Выберите услугу",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="meddiag.services",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["patient", "services"],
            },
        ),
    ]
