# Generated by Django 6.0.7 on 2026-08-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddiag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="direction",
            name="image",
            field=models.ImageField(
                blank=True,
                default="media/images/default.jpg",
                help_text="Прикрепите иконку вида диагностики",
                null=True,
                upload_to="static/images",
                verbose_name="Иконка вида диагностики",
            ),
        ),
    ]
