# Generated by Django 6.0.7 on 2026-08-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddiag", "0002_direction_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="doctors",
            field=models.ManyToManyField(
                help_text="Укажите врачей оказывающих услугу",
                related_name="doctors_service",
                to="meddiag.doctors",
                verbose_name="Врачи оказывающие услугу",
            ),
        ),
    ]
