# Generated by Django 6.0.7 on 2026-08-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddiag", "0003_services_doctors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="foto",
            field=models.ImageField(
                blank=True,
                default="foto_doctor/default.jpg",
                help_text="Прикрепите фотографию врача",
                null=True,
                upload_to="foto_doctor/",
                verbose_name="Фотография врача",
            ),
        ),
    ]
