# Generated by Django 6.0.7 on 2026-08-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddiag", "0005_appointment_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutCompany",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "small_name",
                    models.CharField(
                        help_text="Укажите название медицинской компании",
                        max_length=100,
                        verbose_name="Название медицинской компании",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Укажите название медицинской компании",
                        max_length=250,
                        verbose_name="Название медицинской компании",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Укажите описание медицинской компании", verbose_name="Описание медицинской компании"
                    ),
                ),
                (
                    "history",
                    models.TextField(
                        help_text="Укажите историю медицинской компании", verbose_name="История медицинской компании"
                    ),
                ),
                ("mission", models.TextField(help_text="Укажите миссию и ценности", verbose_name="Миссия и ценности")),
                ("doctors", models.TextField(help_text="Опишите команду врачей", verbose_name="Команда врачей")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="settings/default.jpg",
                        help_text="Прикрепите эмблему медицинской компании",
                        null=True,
                        upload_to="settings/",
                        verbose_name="Эмблема медицинской компании",
                    ),
                ),
            ],
            options={
                "verbose_name": "О компании",
                "verbose_name_plural": "О компании",
                "ordering": ["small_name", "description"],
            },
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phone",
                    models.CharField(help_text="Укажите номер телефона/ов", max_length=100, verbose_name="Телефон"),
                ),
                ("email", models.CharField(help_text="Укажите email", max_length=100, verbose_name="Email")),
                ("address", models.TextField(help_text="Укажите адрес медицинской компании", verbose_name="Адрес")),
                (
                    "work_days",
                    models.CharField(
                        help_text="Укажите рабочие дни недели", max_length=30, verbose_name="Рабочие дни недели"
                    ),
                ),
                (
                    "hour_start",
                    models.CharField(
                        help_text="Укажите час начала работы", max_length=2, verbose_name="Час начала работы"
                    ),
                ),
                (
                    "hour_end",
                    models.CharField(
                        help_text="Укажите час окончания работы", max_length=2, verbose_name="Час окончания работы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки компании",
                "verbose_name_plural": "Настройки компании",
                "ordering": ["phone"],
            },
        ),
    ]
