# Generated by Django 6.0.7 on 2026-08-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddiag", "0006_aboutcompany_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutcompany",
            name="small_image",
            field=models.ImageField(
                blank=True,
                default="settings/default.jpg",
                help_text="Прикрепите маленькую эмблему медицинской компании",
                null=True,
                upload_to="settings/small_default.png",
                verbose_name="Эмблема маленькая медицинской компании",
            ),
        ),
    ]
