# Generated by Django 6.0.7 on 2026-08-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddiag", "0007_aboutcompany_small_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="hour_end_second",
            field=models.CharField(
                default=18,
                help_text="Укажите не основой час окончания работы",
                max_length=2,
                verbose_name="Не основной час окончания работы",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contacts",
            name="hour_start_second",
            field=models.CharField(
                default=10,
                help_text="Укажите не основной час начала работы",
                max_length=2,
                verbose_name="Не основной час начала работы",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contacts",
            name="map",
            field=models.TextField(
                blank=True, help_text="Вставьте iframe скрипт карты", null=True, verbose_name="iframe cкрипт карты"
            ),
        ),
        migrations.AddField(
            model_name="contacts",
            name="weekend",
            field=models.CharField(
                default=18, help_text="Укажите выходные дни недели", max_length=30, verbose_name="выходные дни недели"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contacts",
            name="work_days_second",
            field=models.CharField(
                default=18,
                help_text="Укажите не основные рабочие дни недели",
                max_length=30,
                verbose_name="Не основные рабочие дни недели",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aboutcompany",
            name="small_image",
            field=models.ImageField(
                blank=True,
                default="settings/small_default.png",
                help_text="Прикрепите маленькую эмблему медицинской компании",
                null=True,
                upload_to="settings/",
                verbose_name="Эмблема маленькая медицинской компании",
            ),
        ),
    ]
