# Generated by Django 6.0.7 on 2026-08-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddiag", "0008_contacts_hour_end_second_contacts_hour_start_second_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutcompany",
            options={
                "ordering": ["small_name", "slogan"],
                "verbose_name": "О компании",
                "verbose_name_plural": "О компании",
            },
        ),
        migrations.RemoveField(
            model_name="aboutcompany",
            name="description",
        ),
        migrations.AddField(
            model_name="aboutcompany",
            name="slogan",
            field=models.TextField(
                default=1111111111111,
                help_text="Укажите слоган медицинской компании",
                verbose_name="Cлоган медицинской компании",
            ),
            preserve_default=False,
        ),
    ]
