# Generated by Django 6.0.7 on 2026-08-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddiag", "0009_alter_aboutcompany_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutcompany",
            name="full_name",
            field=models.CharField(
                help_text="Укажите полное название медицинской компании",
                max_length=250,
                verbose_name="Название полное медицинской компании",
            ),
        ),
        migrations.AlterField(
            model_name="aboutcompany",
            name="small_name",
            field=models.CharField(
                help_text="Укажите короткое название медицинской компании",
                max_length=100,
                verbose_name="Короткое название медицинской компании",
            ),
        ),
    ]
