# Generated by Django 6.0.7 on 2026-08-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meddiag", "0010_alter_aboutcompany_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="map",
            field=models.TextField(
                blank=True,
                help_text="Вставьте код iframe скрипт карты",
                null=True,
                verbose_name="Код iframe cкрипт карты",
            ),
        ),
    ]
